[project]
name = "dbf_reports_indexer"
version = "0.1.0"
description = "Utility for dbf reports indexing"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "vtl" }
]

dependencies = [
    "dbfread>=2.0.7",
    "sqlmodel>=0.0.24",
    "sqlalchemy>=2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4",
    "ruff>=0.12",
]


[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]